name: Build and Deploy Eco-Service Landing

on:
  push:
    branches:
      - master # o main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install and Build
        # Indicamos que este paso se ejecute dentro de la subcarpeta
        working-directory: ./Eco-Service-Landingpage
        run: |
          npm install
          npm run build

      - name: Deploy to Server
        # También indicamos el directorio de trabajo aquí
        working-directory: ./Eco-Service-Landingpage
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Ahora la ruta vuelve a ser simple, porque ya estamos dentro de la carpeta
          script: |
            rsync -av --delete dist/ ${{ secrets.TARGET_DIR }}