name: Build and Deploy Eco-Service Landing

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install and Build
        run: |
          npm ci
          npm run build
      
      
      - name: Deploy with rsync
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          # Llave SSH privada para la autenticación
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # Host del servidor remoto
          REMOTE_HOST: ${{ secrets.HOST }}
          # Usuario del servidor remoto
          REMOTE_USER: ${{ secrets.USERNAME }}
          # Carpeta de origen en el runner de GitHub (nuestra carpeta compilada)
          SOURCE: "dist/"
          # Carpeta de destino en el servidor
          TARGET: ${{ secrets.TARGET_DIR }}
          # Opción para borrar los archivos en el destino que ya no existen en el origen
          ARGS: --delete