name: Build and Deploy Eco-Service Landing

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Clean Remote Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            
            set -e 
            
            echo "Navegando al directorio de destino..."
            # Usa el secret para la ruta, en lugar de escribirla a mano.
            cd ${{ secrets.TARGET_DIR }}
            
            echo "Directorio actual: $(pwd)"
            echo "Limpiando contenido del directorio..."
          
            rm -rf ./*
            echo "Limpieza completada."
      
      - name: Upload New Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          
          target: ${{ secrets.TARGET_DIR }}